# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenSo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GenSo(object):
    def setupUi(self, GenSo):
        GenSo.setObjectName("GenSo")
        GenSo.setWindowModality(QtCore.Qt.WindowModal)
        GenSo.resize(402, 212)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GenSo.sizePolicy().hasHeightForWidth())
        GenSo.setSizePolicy(sizePolicy)
        self.formLayout = QtWidgets.QFormLayout(GenSo)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.generate_button = QtWidgets.QPushButton(GenSo)
        self.generate_button.setObjectName("generate_button")
        self.gridLayout.addWidget(self.generate_button, 3, 1, 1, 1)
        self.show_save_path = QtWidgets.QLineEdit(GenSo)
        self.show_save_path.setObjectName("show_save_path")
        self.gridLayout.addWidget(self.show_save_path, 1, 0, 1, 1)
        self.save_button = QtWidgets.QPushButton(GenSo)
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 1, 1, 1, 1)
        self.show_result = QtWidgets.QLabel(GenSo)
        self.show_result.setAlignment(QtCore.Qt.AlignCenter)
        self.show_result.setObjectName("show_result")
        self.gridLayout.addWidget(self.show_result, 3, 0, 1, 1)
        self.choose_button = QtWidgets.QPushButton(GenSo)
        self.choose_button.setAutoExclusive(True)
        self.choose_button.setObjectName("choose_button")
        self.gridLayout.addWidget(self.choose_button, 0, 1, 1, 1)
        self.show_file_path = QtWidgets.QLineEdit(GenSo)
        self.show_file_path.setObjectName("show_file_path")
        self.gridLayout.addWidget(self.show_file_path, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.gridLayout)

        self.retranslateUi(GenSo)
        QtCore.QMetaObject.connectSlotsByName(GenSo)

    def retranslateUi(self, GenSo):
        _translate = QtCore.QCoreApplication.translate
        GenSo.setWindowTitle(_translate("GenSo", "GenSo V0.1"))
        self.generate_button.setText(_translate("GenSo", "generate"))
        self.save_button.setText(_translate("GenSo", "choose save path"))
        self.show_result.setText(_translate("GenSo", "State:           Ready"))
        self.choose_button.setText(_translate("GenSo", "choose file path"))
